###
# 1 GET All trails 
# STATUS TESTED ✔️
GET http://localhost:4000/api/trails
Content-Type: application/json

###
# 2 GET trail
# STATUS dev ✔️
GET http://localhost:4000/api/trails/1
Content-Type: application/json

###
# 3 Add trail
# STATUS TESTED ✔️
POST http://localhost:4000/api/trails
Content-Type: application/json

{
    "trail": "Whatsup Batman",
    "_id": "2",
    "author": "Batwoman"
}

###
# 4 Update trail API 
# STATUS dev ✔️
PUT http://localhost:4000/api/trails/1
Content-Type: application/json

{
    "trail": "Master Wayne",
    "_id": "1",
    "author": "Wayne"
}

###
# 5 Delete trail API 
# STATUS dev ✔️
DELETE http://localhost:4000/api/trails/1
Content-Type: application/json